# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: ←
SEOTitle: Jerry's Blog
author: Jerry Chow
timezone: Asia/Shanghai
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# 国内用多说
# disqus: Jerry

#Google Analytics https://developers.google.com/analytics/devguides/collection/analyticsjs/
#去_layout/default.html的头文件中去设置.
#google_analytics_id: UA-72808482-1
#google_analytics_domain: auto

# 自定义永久链接
permalink: /blog/:year/:month/:day/:title/

#默认底图
header-img: /img/default-bg.jpg

RSS: feed.xml
categories_path: categories
tags_path: tags
archive_path: archives
about_path: about

BASE_PATH:


# SNS settings

weibo_username:     Jerry-Chow
facebook_username:     Jerry.Chow
github_username:    Jerry-Chow
google_username:  101167914127123982138/posts
RSS: feed.xml
email: Jerry.Chow#MSN.COM
linkedin: Jerry.Chow

anchorjs: true                          # 修改在default.html->footer


# 评论系统
# Duoshuo settings
duoshuo_username: brucezhaor
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
url: "http://Jerry-Chow.github.io" 

# page Sidebar settings
sidebar-about-description: "A future technique geek."
sidebar-avatar: /img/me2.jpg     # img前面加`/`绝对引用。



# Friends
friends: [
	{   
        title: "Menu1",
        href: "http://bzrlc.github.io/about/"
	}
]



